set macligatures
set incsearch
set guifont=Fira\ Code:h12

colorscheme solarized
set background=dark

if has("gui_macvim")
  " Remove `enter full screen` touch bar button
  aunmenu TouchBar.EnterFullScreen
  aunmenu TouchBar.-characterpicker-
  set guioptions=
end

command! PresentingStart :set guifont=Fira\ Code:h16
command! PresentingEnd :set guifont=Fira\ Code:h12
