" Reload .vimrc - :so %
"
" Language specific stuff is located
" in ftplugin and ftdetect folders

" Start pathogen & load plugins
call pathogen#infect('plugins')
call pathogen#helptags()

filetype plugin on

" Tabs
set tabstop=4     " No. of spaces that tab couns for
set shiftwidth=4  " No. of spaces of each step in autoindent
set expandtab     " Tab inserts spaces
set autoindent    " Copy indent from previous line
set smartindent   " Smart indenting when starting newline

" Don't create swap files in Dropbox
au BufRead,BufNewFile *
\ if expand('%:~') =~ '^\~/Dropbox' |
\ set noswapfile |
\ else |
\ set swapfile |
\ endif

" Remove trailing whitespace on save
au BufWritePre * :%s/\s\+$//e

set history=50      " Remember 50 last commands / patterns
set scrolloff=2     " Keeping 2 line margin above/below cursor
set number          " Start each line with line number
set wildignorecase  " Ignore filename case
set ignorecase smartcase
set wildignore=*.pyc

cd /home/karlis/Projects/

" Disable ex mode
map Q <Nop>

" Visual settings
syntax on               " Enable syntax hilghlighting
set guioptions-=r       " Remove scrollbar
set background=dark
set nohlsearch
colorscheme solarized

if has("gui_running")
  set guifont=Mensch\ 10
endif

" Use arrow keys for buffer manipulation
noremap <Left>  :bprevious<cr>
noremap <Right> :bnext<cr>
noremap <Up>    :bdelete<cr>
noremap <Down>  :buffers<cr>

inoremap <Left>  <esc>:bprevious<cr>
inoremap <Right> <esc>:bnext<cr>
inoremap <Up>    <esc>:bdelete<cr>
inoremap <Down>  <esc>:buffers<cr>

set hidden " Allows movement between modified buffers

function! VerticalSplitBuffer(buffer)
    execute "vert belowright sb" a:buffer
endfunction

command! -nargs=1 Vb call VerticalSplitBuffer(<f-args>)
