# Sites that get blocklisted when I'm
# getting some serious shit done.

GSD_BLOCKLIST=(
  'discogs.com'
  'facebook.com'
  'instagram.com'
  'irir.lv'
  'klab.lv'
  'linkedin.com'
  'news.ycombinator.com'
  'reddit.com'
  'slashdot.org'
  'theverge.com'
  'tvnet.lv'
  'twitter.com'
  'youtube.com'
  'lobste.rs'
  'goodreads.com'
  'amazon.com'
  'youneedabudget.com'
  'strava.com'
  'vox.com'
  'letterboxd.com'
  'chess.com'
  'chess24.com'
  'lichess.org'
  'ebird.org'
  'omnivore.app'
  'nytimes.com'
  'xeno-canto.org'
  'dabasdati.lv'
  'toot.lv'
)
